# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Working Papers
    url: '#working_papers'
    weight: 60
  - name: Work in Progress
    url: '#work_in_progress'
    weight: 65
  - name: Teaching
    url: '#teaching'
    weight: 70
  - name: Supervision
    url: '#supervision'
    weight: 80
  - name: CV
    url: pdf/CV.pdf
    weight: 90 

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
